# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener:  true
    allowed_methods_listener:  true
    routing_loader: false
    view:
        view_response_listener:  true

    serializer:
        serialize_null: true
    body_listener:
        enabled: true
        throw_exception_on_unsupported_content_type:  true
        decoders:
            json: fos_rest.decoder.json
    
    # This is required, so normalizer gets exception rather than flattenException, so additional exception data can be accessed
    exception:
        enabled: false

    # exception:
    #     codes:
    #         App\Exception\MyException: 403
    #     messages:
    #         App\Exception\MyException: Forbidden area.
    format_listener:
        # TODO(teawithsand): make these work only for custom controllers to prevent some strange interference
        rules:
            - { path: ^/api/v1/token, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
            - { path: ^/, priorities: ['html', '*/*'], fallback_format: html, prefer_extension: true }
