# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.auth_token_secret_key: "%env(TWS_AUTH_TOKEN_SECRET_KEY)%"
    app.refresh_token_secret_key: "%env(TWS_REFRESH_TOKEN_SECRET_KEY)%"
    app.reset_password_token_secret_key: "%env(TWS_RESET_PASSWORD_TOKEN_SECRET_KEY)%"
    app.recaptcha_secret_key: "%env(RECAPTCHA_SECRET_KEY)%"
    app.recaptcha_public_key: "%env(RECAPTCHA_PUBLIC_KEY)%"

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # TODO(teawithsand): instead of some fancy dynamic data picking, just use separate router
    # It's easier faster and less messy than decorating stuff
    'App\Serializer\User\ProfileContextBuilder':
        decorates: 'api_platform.serializer.context_builder'
        arguments: [ '@App\Serializer\User\ProfileContextBuilder.inner' ]
        autoconfigure: false
        
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
